site_name: ALCF User Guides
nav:
  - Home: index.md

markdown_extensions:
  - footnotes
  - admonition
  - codehilite
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: ["."]  # for root of repo, default since that is where mkdocs.yml is
      # base_path: ["docs"]
      dedent_subsections: True  # experimental; new in 9.10 (2023-03-05)
      check_paths: True
      url_download: True
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
  not_found: warn

repo_name: 'test_markdown_proofread/test_docs'

plugins:
  - include-markdown
  - codeinclude:
      title_mode: pymdownx.tabbed
  - search:
      lang: en
